<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInite405152f0e96cf902526c944bcf88758
{
    public static $prefixLengthsPsr4 = array (
        'E' => 
        array (
            'Eden\\Path\\' => 10,
            'Eden\\Mail\\' => 10,
            'Eden\\File\\' => 10,
            'Eden\\Core\\' => 10,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Eden\\Path\\' => 
        array (
            0 => __DIR__ . '/..' . '/eden/path/src',
        ),
        'Eden\\Mail\\' => 
        array (
            0 => __DIR__ . '/..' . '/eden/mail/src',
        ),
        'Eden\\File\\' => 
        array (
            0 => __DIR__ . '/..' . '/eden/file/src',
        ),
        'Eden\\Core\\' => 
        array (
            0 => __DIR__ . '/..' . '/eden/core/src',
        ),
    );

    public static $classMap = array (
        'Eden' => __DIR__ . '/..' . '/eden/core/src/Decorator.php',
        'Eden_Array_Argument' => __DIR__ . '/..' . '/eden/array/src/Argument.php',
        'Eden_Array_Base' => __DIR__ . '/..' . '/eden/array/src/Base.php',
        'Eden_Array_Exception' => __DIR__ . '/..' . '/eden/array/src/Exception.php',
        'Eden_Array_Index' => __DIR__ . '/..' . '/eden/array/src/Index.php',
        'Eden_String_Argument' => __DIR__ . '/..' . '/eden/string/src/Argument.php',
        'Eden_String_Base' => __DIR__ . '/..' . '/eden/string/src/Base.php',
        'Eden_String_Exception' => __DIR__ . '/..' . '/eden/string/src/Exception.php',
        'Eden_String_Index' => __DIR__ . '/..' . '/eden/string/src/Index.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInite405152f0e96cf902526c944bcf88758::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInite405152f0e96cf902526c944bcf88758::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInite405152f0e96cf902526c944bcf88758::$classMap;

        }, null, ClassLoader::class);
    }
}
