<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Eden\\Path\\' => array($vendorDir . '/eden/path/src'),
    'Eden\\Mail\\' => array($vendorDir . '/eden/mail/src'),
    'Eden\\File\\' => array($vendorDir . '/eden/file/src'),
    'Eden\\Core\\' => array($vendorDir . '/eden/core/src'),
);
